music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :users, only: [:new, :show, :create]

resource :session, only: [:new, :create, :destroy]

resources :bands
end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true
end

music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :session_token, presence: true, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}
  after_initialize :ensure_session_token

  attr_reader :password

  # def self.generate_session_token
  #   SecureRandom.urlsafe_base64(16)
  # end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

  def password=(password)

    @password = password
    self.password_digest = BCrypt::Password.create(password)
    # self.save!c
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    @user = User.find_by(email: email)
    @user.is_password?(password) ? @user : nil
  end
end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login_user!
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    session[:session_token] = @user.reset_session_token!
    redirect_to user_url(@user)
  end

  def logout_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end
end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :index
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save!
      redirect_to bands_url
    else
      flash.now[:errors] = @bands.errors.full_message
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])

    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_message
      redirect_to :edit
    end
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])

    if @user.nil?
      flash.now[:errors] = ["Incorrect username/password"]
      render :new
    else
      login_user!
    end
  end

  def destroy
      logout_user!
      render :new
  end
end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
    render :show
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save!
      login_user!
    else
      flash.now[:errors] = ["Incorrect Email or Password"]
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/app/views/bands/_band.html.erb
<ul>
  <li> <%= band.name %> </li>

  <% if action == :show %>
    <li>
      <a href="<%= edit_band_url(band) %>">Edit <%= band.name %></a>
    </li>

    <li><a href="<%= bands_url %>">Band Index</a> </li>

  <% else %>
    <li><a href="<%= band_url(band) %>">Band Page</a> </li>
  <% end %>

  <li>
    <form action="<%= band_url(band) %>" method="post">
      <input type="hidden" name="_method" value="DELETE">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <input type="submit" value="Delete Band">
    </form>
  </li>
</ul>

music_app/app/views/bands/_form.html.erb
<% if action == :new %>
    <% action_url = bands_url %>
    <% button_text = "Create Band" %>
    <h2>Create A New Band</h2>
<% else %>
    <% action_url = band_url(band) %>
    <% button_text = "Update Band" %>
    <h2>Update A Band</h2>
<% end %>



<form action="<%= action_url %>" method="post">
  <% unless action == :new %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="band_name">Band Name</label>
  <input type="text" name="band[name]" value="<%= band.name %>" id="band_name">

  <input type="submit" value="<%= button_text %>">
</form>

music_app/app/views/bands/edit.html.erb
<%= render 'form', band: @band, action: :edit %>

music_app/app/views/bands/index.html.erb
<h2>All Bands</h2>

<ul>
  <% @bands.each do |curr_band| %>
  <li> <%= render 'band', band: curr_band, action: :index %> </li>
  <% end %>
</ul>

music_app/app/views/bands/new.html.erb
<%= render 'form', band: @band, action: :new %>

music_app/app/views/bands/show.html.erb
<%= render 'band', band: @band, action: :show %>

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <header>
      <h1>
        Music App
      </h1>
      <% unless current_user %>
          <form action="<%= new_session_url %>" method="get">
            <input type="submit" value="Log In">
          </form>

          <form action="<%= new_user_url %>" method="get">
            <input type="submit" value="Sign Up">
          </form>
        <% else %>
          <form action="<%= session_url %>" method="post">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <input type="hidden" name="_method" value="delete">
            <input type="submit" value="Log Out">
          </form>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>

music_app/app/views/users/new.html.erb
<h2>Sign Up Here!</h2>

<form action="<%= users_url(@user) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="user_email">Email</label>
  <input type="text"
    name="user[email]"
    id="user_email"
    value = "<%= @user.email %>">
  <br>

  <label for="user_password">Password</label>
  <input type="password"
    name="user[password]"
    id="user_password"
    value = "<%= @user.email %>">
  <br>

  <input type="submit" value="Sign Up">
</form>

music_app/app/views/users/show.html.erb
<h1><%= @user[:email] %></h1>